apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "js-agent.fullname" . }}
  labels:
    {{- include "js-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "js-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "js-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "js-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-drill-admin-service
          image: groundnuty/k8s-wait-for:v1.3
          args:
            - "service"
            - "-lapp.kubernetes.io/name=admin"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: APP_PORT
              value: "{{ .Values.APP_PORT }}"
            - name: WAIT_HOSTS
              value: "{{ .Values.WAIT_HOSTS }}"
            - name: DRILL_ADMIN_PROTOCOL
              value: "{{ .Values.DRILL_ADMIN_PROTOCOL }}"
            - name: COVERAGE_SOURCE_OMIT_PREFIX
              value: "{{ .Values.COVERAGE_SOURCE_OMIT_PREFIX }}"
            - name: COVERAGE_SOURCE_APPEND_PREFIX
              value: "{{ .Values.COVERAGE_SOURCE_APPEND_PREFIX }}"
            - name: PERF_MEASUREMENT_ENABLED
              value: "{{ .Values.PERF_MEASUREMENT_ENABLED }}"
            - name: PERF_DIFFS_ENABLED
              value: "{{ .Values.PERF_DIFFS_ENABLED }}"
            - name: DEBUG_AGENT_SERVICE_CONNECTION
              value: "{{ .Values.DEBUG_AGENT_SERVICE_CONNECTION }}"
            - name: DEBUG_AGENT_SERVICE_CONNECTION_MAX_ARGS_LENGTH
              value: "{{ .Values.DEBUG_AGENT_SERVICE_CONNECTION_MAX_ARGS_LENGTH }}"
            - name: DRILL_ADMIN_HOST
              value: "{{ .Values.DRILL_ADMIN_HOST }}"
            - name: MONGO_HOST
              value: "{{ .Values.MONGO_HOST }}"
            - name: MONGO_DBNAME
              value: "{{ .Values.MONGO_DBNAME }}"
            - name: DEBUG
              value: "{{ .Values.DEBUG }}"
            - name: DEBUG_COLORS
              value: "{{ .Values.DEBUG_COLORS }}"
            - name: FORCE_COLOR
              value: "{{ .Values.FORCE_COLOR }}"
            - name: DEBUG_LOG_LEVEL
              value: "{{ .Values.DEBUG_LOG_LEVEL }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: port9404
              containerPort: 9404
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9404
          readinessProbe:
            httpGet:
              path: /
              port: 9404
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
