apiVersion: v1
kind: Service
metadata:
  name: {{ include "js-agent.fullname" . }}
  labels:
    {{- include "js-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9404
      protocol: TCP
      name: port9404
  selector:
    {{- include "js-agent.selectorLabels" . | nindent 4 }}
