apiVersion: v1
kind: Service
metadata:
  name: {{ include "browser-proxy.fullname" . }}
  labels:
    {{- include "browser-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7777
      protocol: TCP
      name: port7777
  selector:
    {{- include "browser-proxy.selectorLabels" . | nindent 4 }}
