apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotest-extension-dispatcher.fullname" . }}
  labels:
    {{- include "autotest-extension-dispatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5003
      protocol: TCP
      name: port5003
  selector:
    {{- include "autotest-extension-dispatcher.selectorLabels" . | nindent 4 }}
