apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaagent
  labels:
    app.kubernetes.io/name: admin-javaagent
    app.kubernetes.io/instance: drill-admin-javaagent
spec:
  # serviceName: javaagent
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-javaagent
      app.kubernetes.io/instance: drill-admin-javaagent
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: admin-javaagent
        app.kubernetes.io/instance: drill-admin-javaagent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imagejavaagent.repository }}:{{ .Values.imagejavaagent.tag }}"
          env:
            - name: AGENT_VERSION
              value: 0.7.0-30
            - name: AUTOTEST_AGENT_VERSION
              value: 0.16.2
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          volumeMounts:
            - mountPath: /data
              name: "agent-files-{{ .Values.imagejavaagent.tag | replace "." "-" }}"
      volumes:
        - name: "agent-files-{{ .Values.imagejavaagent.tag | replace "." "-" }}"
          persistentVolumeClaim:
            claimName: "agent-files-{{ .Values.imagejavaagent.tag | replace "." "-" }}"
